FROM flink:2.3.0-scala_2.12 AS flink_distribution

FROM apache/airflow:2.10.5

USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends openjdk-17-jre-headless \
    && rm -rf /var/lib/apt/lists/*
COPY --from=flink_distribution --chown=airflow:root /opt/flink /opt/flink

COPY --chown=airflow:root requirements.txt /tmp/project-requirements.txt
USER airflow
RUN pip install --no-cache-dir -r /tmp/project-requirements.txt

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH=/opt/flink/bin:${PATH}
