FROM flink:2.2.0-scala_2.12

USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends python3 python3-pip \
    && pip3 install --break-system-packages --no-cache-dir apache-flink==2.2.0 \
    && chmod -R 777 /opt/flink/conf \
    && rm -rf /var/lib/apt/lists/*

USER flink
